### PR TITLE
Use Travis' scala version environment variable correctly.

### PR DESCRIPTION
**Pull request by 2rs2ts**

### CODE REVIEW

**Comment by 2rs2ts** [comment]
These failures are expected. Cascade hasn't compiled under 2.10 since #136 was merged (but I never noticed because the builds weren't cross-compiling.)

**Comment by devmage** [comment]
It stands to some reason to revisit this after we've merged #144

**Comment by 2rs2ts** [comment]
@devmage It will work once we drop 2.10. What's nice about this PR is that it will continue to work into the future if we cross-compile again.

**Comment by 2rs2ts** [comment]
@devmage So should I go ahead and merge this?

**Comment by devmage** [comment]
>  I'm bulletproof.
> Nothing to lose.
> Fire away, fire away.

@2rs2ts yes, :shipit: , and thanks

**Pull request merged**
