### PR TITLE
Add suchThat size constraints to List and String generators

### PR DESCRIPTION
**Pull request by 2rs2ts**
See https://github.com/rickynils/scalacheck/issues/129.

### CODE REVIEW

**Comment by arschles** [comment]
@2rs2ts are you waiting for https://github.com/rickynils/scalacheck/issues/129 before you merge this? also, I'm concerned with `suchThat` causing generators to exhaust before a satisfactory number of runs and causing false negatives in the test. is that going to be a problem?

**Comment by 2rs2ts** [comment]
@arschles This is not imposing any additional constraints, it just re-attaches the predicate so that shrinking will work properly. The gist of the problem is that you have to always have `suchThat` at the very end of everything.

**Comment by arschles** [comment]
Got it. Thanks for that clarification

**Comment by taylorleese** [comment]
@2rs2ts Please add some comments in the file related to when/why ```.suchThat``` should be used for shrinking to work properly.

**Pull request merged**
