### PR TITLE
Release/0.4.9

### PR DESCRIPTION
**Pull request by msv**
* `SprayConfiguration` now lets you override the spray `RejectionHandler` (see #128)
* "service-version" added to status endpoint (see #138)
* specs2 upgraded to 3.6 (see #136)
* various other improvements

### CODE REVIEW

**Comment by 2rs2ts** [comment]
I hope you don't mind that I put a brief changelog in your PR comment for you :)

**Comment by msv** [comment]
@2rs2ts np thanks

**Comment by oliviazhang0809** [comment]
[Job549.3](https://travis-ci.org/paypal/cascade/jobs/63058914) =>
```
:::: ERRORS
	Server access Error: Connection timed out url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.8/ivys/ivy.xml
```

[Job549.4](https://travis-ci.org/paypal/cascade/jobs/63058915) =>
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.jsuereth#pgp-library_2.10;1.0.0!pgp-library_2.10.jar
[warn] 	:: net.databinder#dispatch-http_2.10;0.8.10!dispatch-http_2.10.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: com.jsuereth#pgp-library_2.10;1.0.0!pgp-library_2.10.jar
```

**Comment by 2rs2ts** [comment]
Yeah, I'm restarting those jobs. No reason why they should fail if their dependencies could be fetched.

**Comment by oliviazhang0809** [comment]
nice it's good now~

**Comment by 2rs2ts** [comment]
Due to cascade not compiling for 2.10 (see https://github.com/etorreborre/specs2/issues/379) we are just going to release this for 2.11. We are going to drop 2.10 support in the next release.

**Pull request merged**
