### PR TITLE
Remove release.sh

### PR DESCRIPTION
**Pull request by taylorleese**
Use instructions added in https://github.com/paypal/cascade/pull/47 instead

### CODE REVIEW

**Comment by ronnieftw** [comment]
:shipit:

**Comment by arschles** [comment]
release instructions are still multi-step. I want an easier way to release, so can we bring the script back

**Comment by taylorleese** [comment]
@arschles The script isn't very useful. If you want to bring it back then update the instructions to work with the release instructions to exhibit why it's necessary.

**Comment by taylorleese** [comment]
@arschles Note, this is also an effort to make sure people are releasing following the same process. Neither your original release instructions or mine mentioned the use of the script.

**Pull request merged**
