### PR TITLE
Drop 2.10 support

### LINKED ISSUE #143: Drop 2.10 support

### PR DESCRIPTION
**Pull request by 2rs2ts**
Fixes #143 as it were.

### CODE REVIEW

**Comment by devmage** [comment]
For future record, we took a poll of the PayPal-side maintainers, and majority opinion was to remove 2.10 support as such.

**Comment by devmage** [comment]
@2rs2ts so the idea here would be for 0.4 to be the last line that supports 2.10, with 0.5 and on being 2.11-only, yes?

**Comment by 2rs2ts** [comment]
@devmage Yes. Although I had to release 0.4.9 with just 2.11 anyway, because I haven't gotten it to compile with 2.10. If I can get help with that, then I'll gladly release 0.4.10 separately.

**Comment by devmage** [comment]
@2rs2ts unfortunate about that, then. I support your plan to release a 0.4.10 from the current 0.4.9 mark, and carry on forward with 0.5+ as 2.11-only. Let's just be sure to revisit 0.4.10 when it's feasible.

:shipit:

**Pull request merged**
