### PR TITLE
gen-idea is deprecated. Remove it.

### PR DESCRIPTION
**Pull request by 2rs2ts**

### CODE REVIEW

**Comment by devmage** [comment]
I've been advising against using sbt-idea since at least IntelliJ 13, happy to endorse this. :shipit:

**Comment by ayakushev99** [comment]
I use gen-idea, sbt plugin hasn't always been working correctly. I don't see a reason to remove it, it's not hurting anything.

**Comment by wpalmeri** [comment]
i was using gen-idea too due to being distrustful of the intellij plugin

**Comment by kionka** [comment]
Well, everybody else has switched since we follow warnings.

**Comment by 2rs2ts** [comment]
Related: https://github.com/mpeltonen/sbt-idea/issues/324

If you need gen-idea then add the following to `~/.sbt/0.13/plugins/build.sbt`:

    addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.2")

As documented [here](http://www.scala-sbt.org/0.13/docs/Global-Settings.html).

**Comment by devmage** [comment]
@wpalmeri @ayakushev99 using `sbt-idea` to generate IntelliJ project files is presently an antipattern. We don't need it anymore, the Scala plugin since circa IntelliJ 13 has been pretty strong. I can't recall a single problem that I've had in the IntelliJ 14 series plugin.

YMMV. I'd recommend importing a few SBT projects in IntelliJ 14 just to see. I'd be very interested to know if you run into problems.

**Pull request merged**
